# FlexFile Data Spec for building database

flexfile_spec <- list(accounts = list(type = "table",
                                      table = "accounts",
                                      fields = c(doc_id = "LONG",
                                                 id = "VARCHAR",
                                                 name = "VARCHAR"),
                                      pk = c("doc_id", "id")),

                      actualcosthourdata = list(type = "table",
                                                table = "actualcosthourdata",
                                                fields = c(doc_id = "LONG",
                                                           order_or_lot_id = "VARCHAR",
                                                           clin_id = "VARCHAR",
                                                           end_item_id = "VARCHAR",
                                                           wbs_element_id = "VARCHAR",
                                                           account_id = "VARCHAR",
                                                           nonrecurring_or_recurring_id = "VARCHAR",
                                                           functional_category_id = "VARCHAR",
                                                           functional_overhead_category_id = "VARCHAR",
                                                           standard_category_id = "VARCHAR",
                                                           detailed_standard_category_id = "VARCHAR",
                                                           unit_or_sublot_id = "VARCHAR",
                                                           allocation_method_id = "VARCHAR",
                                                           reporting_period_id = "LONG",
                                                           tag1 = "VARCHAR",
                                                           tag2 = "VARCHAR",
                                                           tag3 = "VARCHAR",
                                                           tag4 = "VARCHAR",
                                                           tag5 = "VARCHAR",
                                                           tag6 = "VARCHAR",
                                                           tag7 = "VARCHAR",
                                                           tag8 = "VARCHAR",
                                                           tag9 = "VARCHAR",
                                                           tag10 = "VARCHAR",
                                                           tag11 = "VARCHAR",
                                                           tag12 = "VARCHAR",
                                                           tag13 = "VARCHAR",
                                                           tag14 = "VARCHAR",
                                                           tag15 = "VARCHAR",
                                                           tag16 = "VARCHAR",
                                                           tag17 = "VARCHAR",
                                                           tag18 = "VARCHAR",
                                                           tag19 = "VARCHAR",
                                                           tag20 = "VARCHAR",
                                                           tag21 = "VARCHAR",
                                                           tag22 = "VARCHAR",
                                                           tag23 = "VARCHAR",
                                                           tag24 = "VARCHAR",
                                                           tag25 = "VARCHAR",
                                                           value_dollars = "DOUBLE",
                                                           value_hours = "DOUBLE"),
                                                pk = vector("character")),

                      allocationcomponents = list(type = "table",
                                                  table = "allocationcomponents",
                                                  fields = c(doc_id = "LONG",
                                                             allocation_method_id = "VARCHAR",
                                                             order_or_lot_id = "VARCHAR",
                                                             end_item_id = "VARCHAR",
                                                             wbs_element_id = "VARCHAR",
                                                             unit_or_sublot_id = "VARCHAR",
                                                             percent_value = "DOUBLE"),
                                                   pk = c("doc_id",
                                                          "allocation_method_id",
                                                          "order_or_lot_id",
                                                          "end_item_id",
                                                          "wbs_element_id",
                                                          "unit_or_sublot_id")),

                      allocationmethods = list(type = "table",
                                               table = "allocationmethods",
                                               fields = c(doc_id = "LONG",
                                                          id = "VARCHAR",
                                                          allocation_method_type_id = "VARCHAR",
                                                          is_unit_or_sublot_allocation_method = "BIT",
                                                          name = "VARCHAR"),
                                               pk = c("doc_id",
                                                      "id")),

                      clins = list(type = "table",
                                   table = "clins",
                                   fields = c(doc_id = "LONG",
                                              id = "VARCHAR",
                                              name = "VARCHAR",
                                              contract_type_id = "VARCHAR"),
                                   pk = c("doc_id",
                                          "id")),

                      costhourdatatagedefinitions = list(type = "table",
                                                         table = "costhourdatatagdefinitions",
                                                         fields = c(doc_id = "LONG",
                                                                    cost_hour_tag_id = "VARCHAR",
                                                                    name = "VARCHAR",
                                                                    definition = "VARCHAR"),
                                                         pk = c("doc_id",
                                                                "cost_hour_tag_id")),

                      enditems = list(type = "table",
                                      table = "enditems",
                                      fields = c(doc_id = "LONG",
                                                 id = "VARCHAR",
                                                 name = "VARCHAR"),
                                      pk = c("doc_id",
                                             "id")),

                      forecastatcompletioncosthourdata = list(type = "table",
                                                              table = "forecastatcompletioncosthourdata",
                                                              fields = c(doc_id = "LONG",
                                                                         order_or_lot_id = "VARCHAR",
                                                                         wbs_element_id = "VARCHAR",
                                                                         nonrecurring_or_recurring_id = "VARCHAR",
                                                                         standard_category_id = "VARCHAR",
                                                                         detailed_standard_category_id = "VARCHAR",
                                                                         value_dollars = "DOUBLE",
                                                                         value_hours = "DOUBLE"),
                                                              pk = c("doc_id",
                                                                     "order_or_lot_id",
                                                                     "wbs_element_id",
                                                                     "nonrecurring_or_recurring_id",
                                                                     "standard_category_id",
                                                                     "detailed_standard_category_id")),

                      functionalcategories = list(type = "table",
                                                  table = "functionalcategories",
                                                  fields = c(doc_id = "LONG",
                                                             id = "VARCHAR",
                                                             name = "VARCHAR"),
                                                  pk = c("doc_id",
                                                         "id")),

                      functionaloverheadcategories = list(type = "table",
                                                          table = "functionaloverheadcategories",
                                                          fields = c(doc_id = "LONG",
                                                                     id = "VARCHAR",
                                                                     name = "VARCHAR"),
                                                          pk = c("doc_id",
                                                                 "id")),

                      ordersorlots = list(type = "table",
                                          table = "ordersorlots",
                                          fields = c(doc_id = "LONG",
                                                     id = "VARCHAR",
                                                     name = "VARCHAR",
                                                     phase_or_milestone_id = "VARCHAR",
                                                     customer_name = "VARCHAR",
                                                     contract_type_id = "VARCHAR",
                                                     contract_price = "DOUBLE",
                                                     contract_ceiling = "DOUBLE",
                                                     period_of_performance_start_date = "DATETIME",
                                                     period_of_performance_end_data = "DATETIME",
                                                     appropriation_type_id = "VARCHAR"),
                                           pk = c("doc_id",
                                                  "id")),

                      reportconfiguration = list(type = "table",
                                                 table = "reportconfiguration",
                                                 fields = c(doc_id = "LONG",
                                                            detailed_standard_category = "BIT",
                                                            ga_as_standard_category = "BIT",
                                                            fccm_as_standard_category = "BIT",
                                                            forecast_at_completion_by_nonrecurring_or_recurring = "BIT",
                                                            forecast_at_completion_by_standard_category = "BIT"),
                                                  pk = vector("character")),

                      reportingcalendar = list(type = "table",
                                               table = "reportingcalendar",
                                               fields = c(doc_id = "LONG",
                                                          id = "LONG",
                                                          start_date = "DATETIME",
                                                          end_date = "DATETIME"),
                                               pk = c("doc_id",
                                                      "id")),

                      reportmetadata = list(type = "table",
                                            table = "reportmetadata",
                                            fields = c(doc_id = "LONG",
                                                       security_classification = "VARCHAR",
                                                       proprietary_statement = "VARCHAR",
                                                       program_name = "VARCHAR",
                                                       phase_or_milestone_id = "VARCHAR",
                                                       prime_mission_product = "VARCHAR",
                                                       commodity_type = "VARCHAR",
                                                       reporting_organization_name = "VARCHAR",
                                                       reporting_organization_division = "VARCHAR",
                                                       reporting_organization_cage_code = "VARCHAR",
                                                       reporting_organization_location_street = "VARCHAR",
                                                       reporting_organization_location_city = "VARCHAR",
                                                       reporting_organization_location_state = "VARCHAR",
                                                       reporting_organization_zip_code = "VARCHAR",
                                                       reporting_organization_country = "VARCHAR",
                                                       approved_plan_number = "VARCHAR",
                                                       approved_plan_revision_number = "VARCHAR",
                                                       customer_name = "VARCHAR",
                                                       contract_type_id = "VARCHAR",
                                                       contract_price = "DOUBLE",
                                                       contract_ceiling = "DOUBLE",
                                                       contract_number = "VARCHAR",
                                                       period_of_performance_start_date = "DATETIME",
                                                       period_of_performance_end_date = "DATETIME",
                                                       report_cycle_id = "VARCHAR",
                                                       submission_event_number = "LONG",
                                                       submission_event_name = "VARCHAR",
                                                       submission_event_is_wildcard = "BIT",
                                                       resubmission_number = "LONG",
                                                       report_as_of = "VARCHAR",
                                                       point_of_contact_name = "VARCHAR",
                                                       point_of_contact_department = "VARCHAR",
                                                       point_of_contact_telephone_number = "VARCHAR",
                                                       point_of_contact_email_address = "VARCHAR",
                                                       date_prepared = "VARCHAR",
                                                       reporting_period_id = "LONG"),
                                            pk = vector("character")),

                      summarycostdata = list(type = "table",
                                             table = "summarycostdata",
                                             fields = c(doc_id = "LONG",
                                                        order_or_lot_id = "VARCHAR",
                                                        subtotal_td = "DOUBLE",
                                                        subtotal_ac = "DOUBLE",
                                                        ga_td = "DOUBLE",
                                                        ga_ac = "DOUBLE",
                                                        ub = "DOUBLE",
                                                        mr = "DOUBLE",
                                                        fccm_td = "DOUBLE",
                                                        fccm_ac = "DOUBLE",
                                                        fee_td = "DOUBLE",
                                                        fee_ac = "DOUBLE",
                                                        price_td = "DOUBLE",
                                                        price_ac = "DOUBLE"),
                                             pk = c("doc_id",
                                                    "order_or_lot_id")),

                      summaryremarks = list(type = "table",
                                            table = "summaryremarks",
                                            fields = c(doc_id = "LONG",
                                                       order_or_lot_id = "VARCHAR",
                                                       remarks = "VARCHAR"),
                                            pk = c("doc_id",
                                                   "order_or_lot_id")),

                      unitsorsublots = list(type = "table",
                                            table = "unitsorsublots",
                                            fields = c(doc_id = "LONG",
                                                       id = "VARCHAR",
                                                       end_item_id = "VARCHAR",
                                                       first_unit_number = "LONG",
                                                       last_unit_number = "LONG",
                                                       order_or_lot_id = "VARCHAR"),
                                            pk = c("doc_id",
                                                   "id")),

                      wbs = list(type = "table",
                                 table = "wbs",
                                 fields = c(doc_id = "LONG",
                                            level = "LONG",
                                            id = "VARCHAR",
                                            name = "VARCHAR",
                                            parent_id = "VARCHAR"),
                                 pk = c("doc_id",
                                        "id")),

                      wbsdictionarydefinitions = list(type = "table",
                                                      table = "wbsdictionarydefinitions",
                                                      fields = c(doc_id = "LONG",
                                                                 wbs_element_id = "VARCHAR",
                                                                 definitions = "VARCHAR"),
                                                      pk = c("doc_id",
                                                             "wbs_element_id")),

                      wbselementremarks = list(type = "table",
                                               table = "wbselementremarks",
                                               fields = c(doc_id = "LONG",
                                                          order_or_lot_id = "VARCHAR",
                                                          wbs_element_id = "VARCHAR",
                                                          remarks = "VARCHAR"),
                                               pk = c("doc_id",
                                                      "order_or_lot_id",
                                                      "wbs_element_id")),

                      # enumeration tables

                      allocationmethodtypeenum = list(type = "table",
                                                      table = "allocationmethodtypeenum",
                                                      fields = c(id = "VARCHAR",
                                                                 name = "VARCHAR"),
                                                      pk = c("id")),

                      appropriationtypeenum = list(type = "table",
                                                   table = "appropriationtypeenum",
                                                   fields = c(id = "VARCHAR",
                                                              name = "VARCHAR"),
                                                   pk = c("id")),

                      contracttypeenum = list(type = "table",
                                              table = "contracttypeenum",
                                              fields = c(id = "VARCHAR",
                                                         name = "VARCHAR"),
                                              pk = c("id")),

                      costhourtagenum = list(type = "table",
                                             table = "costhourtagenum",
                                             fields = c(id = "VARCHAR",
                                                        name = "VARCHAR"),
                                             pk = c("id")),

                      detailedstandardcategoryenum = list(type = "table",
                                                          table = "detailedstandardcategoryenum",
                                                          fields = c(id = "VARCHAR",
                                                                     name = "VARCHAR"),
                                                          pk = c("id")),

                      nonrecurringorrecurringenum = list(type = "table",
                                                         table = "nonrecurringorrecurringenum",
                                                         fields = c(id = "VARCHAR",
                                                                    name = "VARCHAR"),
                                                         pk = c("id")),

                      phaseormilestoneenum = list(type = "table",
                                                  table = "phaseormilestoneenum",
                                                  fields = c(id = "VARCHAR",
                                                             name = "VARCHAR"),
                                                  pk = c("id")),

                      reportcycleenum = list(type = "table",
                                             table = "reportcycleenum",
                                             fields = c(id = "VARCHAR",
                                                        name = "VARCHAR"),
                                             pk = c("id")),

                      standardcategoryenum = list(type = "table",
                                                  table = "standardcategoryenum",
                                                  fields = c(id = "VARCHAR",
                                                             name = "VARCHAR"),
                                                  pk = c("id")),

                      # constraints

                      actualcosthourdata_fk01 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "ordersorlots",
                                                     by = c("doc_id" = "doc_id",
                                                            "order_or_lot_id" = "id")),

                      actualcosthourdata_fk02 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "enditems",
                                                     by = c("doc_id" = "doc_id",
                                                            "end_item_id" = "id")),

                      actualcosthourdata_fk03 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "wbs",
                                                     by = c("doc_id" = "doc_id",
                                                            "wbs_element_id" = "id")),

                      actualcosthourdata_fk04 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "accounts",
                                                     by = c("doc_id" = "doc_id",
                                                            "account_id" = "id")),

                      actualcosthourdata_fk05 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "functionalcategories",
                                                     by = c("doc_id" = "doc_id",
                                                            "functional_category_id" = "id")),

                      actualcosthourdata_fk06 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "functionaloverheadcategories",
                                                     by = c("doc_id" = "doc_id", "functional_overhead_category_id" = "id")),

                      actualcosthourdata_fk07 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "unitsorsublots",
                                                     by = c("doc_id" = "doc_id", "unit_or_sublot_id" = "id")),

                      actualcosthourdata_fk08 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "allocationmethods",
                                                     by = c("doc_id" = "doc_id", "allocation_method_id" = "id")),

                      actualcosthourdata_fk09 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "reportingcalendar",
                                                     by = c("doc_id" = "doc_id", "reporting_period_id" = "id")),

                      actualcosthourdata_fk10 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "standardcategoryenum",
                                                     by = c("standard_category_id" = "id")),

                      actualcosthourdata_fk11 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "detailedstandardcategoryenum",
                                                     by = c("detailed_standard_category_id" = "id")),

                      actualcosthourdata_fk12 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "clins",
                                                     by = c("doc_id" = "doc_id", "clin_id" = "id")),

                      actualcosthourdata_fk13 = list(type = "constraint",
                                                     table = "actualcosthourdata",
                                                     ref_table = "nonrecurringorrecurringenum",
                                                     by = c("nonrecurring_or_recurring_id" = "id")),

                      allocationcomponents_fk01 = list(type = "constraint",
                                                       table = "allocationcomponents",
                                                       ref_table = "allocationmethods",
                                                       by = c("doc_id" = "doc_id",
                                                              "allocation_method_id" = "id")),

                      allocationcomponents_fk02 = list(type = "constraint",
                                                       table = "allocationcomponents",
                                                       ref_table = "ordersorlots",
                                                       by = c("doc_id" = "doc_id",
                                                              "order_or_lot_id" = "id")),

                      allocationcomponents_fk03 = list(type = "constraint",
                                                       table = "allocationcomponents",
                                                       ref_table = "enditems",
                                                       by = c("doc_id" = "doc_id",
                                                              "end_item_id" = "id")),

                      allocationcomponents_fk04 = list(type = "constraint",
                                                       table = "allocationcomponents",
                                                       ref_table = "wbs",
                                                       by = c("doc_id" = "doc_id",
                                                              "wbs_element_id" = "id")),

                      allocationcomponents_fk05 = list(type = "constraint",
                                                       table = "allocationcomponents",
                                                       ref_table = "unitsorsublots",
                                                       by = c("doc_id" = "doc_id",
                                                              "unit_or_sublot_id" = "id")),

                      allocationmethods_fk01 = list(type = "constraint",
                                                    table = "allocationmethods",
                                                    ref_table = "allocationmethodtypeenum",
                                                    by = c("allocation_method_type_id" = "id")),

                      clins_fk01 = list(type = "constraint",
                                        table = "clins",
                                        ref_table = "contracttypeenum",
                                        by = c("contract_type_id" = "id")),

                      costhourdatatagdefinitions_fk01 = list(type = "constraint",
                                                              table = "costhourdatatagdefinitions",
                                                              ref_table = "costhourtagenum",
                                                              by = c("cost_hour_tag_id" = "id")),

                      forecastatcompletioncosthourdata_fk01 = list(type = "constraint",
                                                                   table = "forecastatcompletioncosthourdata",
                                                                   ref_table = "ordersorlots",
                                                                   by = c("doc_id" = "doc_id", "order_or_lot_id" = "id")),

                      forecastatcompletioncosthourdata_fk02 = list(type = "constraint",
                                                                   table = "forecastatcompletioncosthourdata",
                                                                   ref_table = "wbs",
                                                                   by = c("doc_id" = "doc_id", "wbs_element_id" = "id")),

                      forecastatcompletioncosthourdata_fk03 = list(type = "constraint",
                                                                   table = "forecastatcompletioncosthourdata",
                                                                   ref_table = "standardcategoryenum",
                                                                   by = c("standard_category_id" = "id")),

                      forecastatcompletioncosthourdata_fk04 = list(type = "constraint",
                                                                   table = "forecastatcompletioncosthourdata",
                                                                   ref_table = "detailedstandardcategoryenum",
                                                                   by = c("detailed_standard_category_id" = "id")),

                      forecastatcompletioncosthourdata_fk05 = list(type = "constraint",
                                                                   table = "forecastatcompletioncosthourdata",
                                                                   ref_table = "nonrecurringorrecurringenum",
                                                                   by = c("nonrecurring_or_recurring_id" = "id")),

                      ordersorlots_fk01 = list(type = "constraint",
                                               table = "ordersorlots",
                                               ref_table = "phaseormilestoneenum",
                                               by = c("phase_or_milestone_id" = "id")),

                      ordersorlots_fk02 = list(type = "constraint",
                                               table = "ordersorlots",
                                               ref_table = "contracttypeenum",
                                               by = c("contract_type_id" = "id")),

                      ordersorlots_fk03 = list(type = "constraint",
                                               table = "ordersorlots",
                                               ref_table = "appropriationtypeenum",
                                               by = c("appropriation_type_id" = "id")),

                      reportmetadata_fk01 = list(type = "constraint",
                                                 table = "reportmetadata",
                                                 ref_table = "phaseormilestoneenum",
                                                 by = c("phase_or_milestone_id" = "id")),

                      reportmetadata_fk02 = list(type = "constraint",
                                                 table = "reportmetadata",
                                                 ref_table = "contracttypeenum",
                                                 by = c("contract_type_id" = "id")),

                      reportmetadata_fk03 = list(type = "constraint",
                                                 table = "reportmetadata",
                                                 ref_table = "reportcycleenum",
                                                 by = c("report_cycle_id" = "id")),

                      reportmetadata_fk04 = list(type = "constraint",
                                                 table = "reportmetadata",
                                                 ref_table = "reportingcalendar",
                                                 by = c("doc_id" = "doc_id",
                                                        "reporting_period_id" = "id")),

                      summarycostdata_fk01 = list(type = "constraint",
                                                  table = "summarycostdata",
                                                  ref_table = "ordersorlots",
                                                  by = c("doc_id" = "doc_id",
                                                         "order_or_lot_id" = "id")),

                      summaryremarks_fk01 = list(type = "constraint",
                                                 table = "summaryremarks",
                                                 ref_table = "ordersorlots",
                                                 by = c("doc_id" = "doc_id", "order_or_lot_id" = "id")),

                      unitsorsublots_fk01 = list(type = "constraint",
                                                 table = "unitsorsublots",
                                                 ref_table = "enditems",
                                                 by = c("doc_id" = "doc_id",
                                                        "end_item_id" = "id")),

                      unitsorsublots_fk02 = list(type = "constraint",
                                                 table = "unitsorsublots",
                                                 ref_table = "ordersorlots",
                                                 by = c("doc_id" = "doc_id",
                                                        "order_or_lot_id" = "id")),

                      wbs_fk01 = list(type = "contraint",
                                      table = "wbs",
                                      ref_table = "wbs",
                                      by = c("parent_id" = "id")),

                      wbsdictionarydefintions_fk01 = list(type = "constraint",
                                                          table = "wbsdictionarydefinitions",
                                                          ref_table = "wbs",
                                                          by = c("doc_id" = "doc_id",
                                                                 "wbs_element_id" = "id")),

                      wbselementremarks_fk01 = list(type = "constraint",
                                                    table = "wbselementremarks",
                                                    ref_table = "ordersorlots",
                                                    by = c("doc_id" = "doc_id",
                                                           "order_or_lot_id" = "id")),

                      wbselementremarks_fk02 = list(type = "constraint",
                                                    table = "wbselementremarks",
                                                    ref_table = "wbs",
                                                    by = c("doc_id" = "doc_id",
                                                           "wbs_element_id" = "id")))


usethis::use_data(flexfile_spec, overwrite = TRUE)
